deploy:
  name: Deploy to ECS
  needs: build
  runs-on: ubuntu-latest

  steps:
    # ✅ Checkout repository in this job
    - name: Checkout repository
      uses: actions/checkout@v4

    # ✅ Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::282378667470:role/GitHubActionsECRRole
        aws-region: us-west-2

    # ✅ Debug: verify template exists
    - name: List repo contents
      run: |
        echo "Root folder:"
        ls -la
        echo "infra folder:"
        ls -la infra
        if [ ! -f infra/ecs-service.yml ]; then
          echo "ERROR: ecs-service.yml not found"
          exit 1
        fi

    # ✅ Deploy CloudFormation
    - name: Deploy CloudFormation stack
      run: |
        IMAGE_URI=282378667470.dkr.ecr.us-west-2.amazonaws.com/slack-cicd-demo:${{ github.sha }}
        aws cloudformation deploy \
          --stack-name slack-cicd-stack \
          --template-file infra/ecs-service.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides ContainerImage=$IMAGE_URI
