AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Service for Slack CI/CD Demo

Parameters:
  ContainerImage:
    Type: String
    Description: Docker image URI

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: slack-cicd-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: slack-cicd-task-execution
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: slack-cicd-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: slack-cicd-container
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 3000

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-08e1b60b2f592fddf
            - subnet-0c4fbee4f301bc8ae
          SecurityGroups:
            - sg-04923c14cae573189
